#!/usr/bin/env perl
# Build script: assembles single-file zepto from modules
use strict;
use warnings;
use File::Find;

# Recursively find all .pm files under lib/
my @all_modules;
find(sub {
    return unless /\.pm$/;
    push @all_modules, $File::Find::name;
}, 'lib');

# Sort modules by dependency order:
# 1. Core modules (no subdir) - sorted alphabetically but with specific order
# 2. Syntax/Base.pm must come before other Syntax modules
# 3. Syntax/* modules alphabetically
# 4. Editor.pm before Editor/* submodules
# 5. Highlighter and Renderer after Syntax modules
# 6. Everything else

my %priority = (
    # Core modules first (lower number = higher priority)
    'lib/Zepto/Buffer.pm'      => 10,
    # VCS modules must come before Document (which uses them)
    'lib/Zepto/VCS/Provider.pm' => 11,  # Provider first (has the registry)
    'lib/Zepto/VCS/Git.pm'      => 12,  # Git second (registers with Provider)
    'lib/Zepto/Diff.pm'         => 13,  # Diff module for VCS
    'lib/Zepto/Document.pm'     => 14,
    'lib/Zepto/View.pm'         => 15,
    'lib/Zepto/InputParser.pm'  => 16,
    'lib/Zepto/Theme.pm'        => 17,
    'lib/Zepto/Preferences.pm'  => 18,
    'lib/Zepto/Terminal.pm'     => 19,
    'lib/Zepto/Config.pm'       => 20,
    'lib/Zepto/Chars.pm'        => 21,
    'lib/Zepto/FileTree.pm'     => 22,
    # Minimap has no Zepto deps — must come before Renderer which derives constants from it
    'lib/Zepto/Minimap.pm'     => 23,
    # Syntax/Base must come first among Syntax modules
    'lib/Zepto/Syntax/Base.pm' => 50,
    # Highlighter needs all Syntax modules loaded
    'lib/Zepto/Highlighter.pm' => 100,
    # Renderer needs Highlighter
    'lib/Zepto/Renderer.pm'    => 110,
    # CommandRegistry must come before Editor (Palette references its constants)
    'lib/Zepto/CommandRegistry.pm' => 115,
    # Editor needs everything above
    'lib/Zepto/Editor.pm'      => 120,
);

sub module_priority {
    my ($path) = @_;

    # Check explicit priority
    return $priority{$path} if exists $priority{$path};

    # Syntax modules (except Base) get priority 60
    return 60 if $path =~ m{lib/Zepto/Syntax/};

    # Editor submodules get priority 130
    return 130 if $path =~ m{lib/Zepto/Editor/};

    # Everything else gets 200
    return 200;
}

my @modules = sort {
    module_priority($a) <=> module_priority($b)
    || $a cmp $b  # Alphabetical within same priority
} @all_modules;

# Header
print <<'HEADER';
#!/usr/bin/env perl
# =============================================================================
# Zepto - A minimal terminal text editor
# =============================================================================
# Single-file distribution. Run: zepto [filename]
# https://github.com/joewalnes/zepto
# 2026 Joe Walnes <joe@walnes.com>
#
# This file is auto-generated by 'make build'. Do not edit directly.
# Edit the source modules in lib/Zepto/ instead.
# =============================================================================

use strict;
use warnings;
use utf8;
use 5.010001;

HEADER

# Include each module
for my $file (@modules) {
    open my $fh, '<', $file or die "Cannot open $file: $!";
    my $content = do { local $/; <$fh> };
    close $fh;

    # Remove shebang if present
    $content =~ s/^#!.*\n//;

    # Convert 'use parent' to @ISA (parent pragma tries to load from filesystem)
    $content =~ s/^use parent\s+'(Zepto::\S+)';\n/our \@ISA = ('$1');\n/gm;

    # Convert Zepto::Syntax::Base import to explicit import call (for Exporter constants)
    # This must happen before removing other use statements
    $content =~ s/^use Zepto::Syntax::Base;[^\n]*\n/BEGIN { Zepto::Syntax::Base->import(); }\n/gm;

    # Remove other 'use Zepto::*' lines (they're all inline now)
    # Handles 'use Zepto::Foo;', 'use Zepto::Foo qw(...);', and lines with trailing comments
    $content =~ s/^use Zepto::\w+(?:::\w+)*(?:\s+qw\([^)]*\))?;[^\n]*\n//gm;

    # Remove __END__ and POD (keep it compact)
    $content =~ s/\n__END__.*//s;

    # Strip comment-only lines (lines starting with #)
    $content =~ s/^[ \t]*#.*\n//gm;

    # Add section header (handle nested modules like Editor/Commands)
    my ($pkg) = $file =~ m{lib/Zepto/(.+)\.pm$};
    $pkg =~ s{/}{::}g;
    print "# " . "=" x 77 . "\n";
    print "# $pkg\n";
    print "# " . "=" x 77 . "\n";

    # Wrap content in a block to create separate lexical scope for each module.
    # This prevents "my variable $X masks earlier declaration" warnings when
    # modules like Syntax::Perl and Syntax::Python both declare my $KEYWORDS.
    print "{\n";
    print $content;
    print "}\n";
    print "\n";
}

# Main entry point
print <<'MAIN';
# =============================================================================
# Main
# =============================================================================
package main;

# Parse command line options
my @files;
my $no_nerd_font = 0;
my $no_tree = 0;

for my $arg (@ARGV) {
    if ($arg eq '--no-nerd-font' || $arg eq '--no-powerline' || $arg eq '-P') {
        $no_nerd_font = 1;
    } elsif ($arg eq '--no-tree') {
        $no_tree = 1;
    } elsif ($arg eq '--help' || $arg eq '-h') {
        print "Usage: zepto [options] [file ...]\n";
        print "Options:\n";
        print "  --no-nerd-font, -P  Disable Nerd Font glyphs\n";
        print "  --no-tree           Hide file tree on startup\n";
        print "  --help, -h          Show this help\n";
        print "\nEnvironment:\n";
        print "  ZEPTO_NERD_FONT=0   Disable Nerd Font glyphs by default\n";
        print "  ZEPTO_TREE=0        Hide file tree by default\n";
        exit 0;
    } elsif ($arg !~ /^-/) {
        push @files, $arg;
    }
}

# Special case: if the only non-option arg is a directory, chdir to it
my $focus_tree = 0;
if (@files == 1 && -d $files[0]) {
    chdir $files[0] or die "Cannot chdir to $files[0]: $!\n";
    @files = ();
    $focus_tree = 1;
}

# Check environment variable for nerd font setting
my $nerd_font = 1;  # Default ON
if ($no_nerd_font || (defined $ENV{ZEPTO_NERD_FONT} && $ENV{ZEPTO_NERD_FONT} eq '0')) {
    $nerd_font = 0;
}

# Determine show_tree: explicit flag > env var > default (hidden when opening files)
my $show_tree = 1;  # Default ON
if ($no_tree || (defined $ENV{ZEPTO_TREE} && $ENV{ZEPTO_TREE} eq '0')) {
    $show_tree = 0;
} elsif (@files >= 1 && !$focus_tree) {
    # Opening specific files (not a directory) — hide tree by default
    $show_tree = 0;
}

# Create preferences
my $prefs = Zepto::Preferences->new(nerd_font => $nerd_font, show_tree => $show_tree);
Zepto::Chars->set_enabled($nerd_font);

my $editor = Zepto::Editor->new(files => \@files, prefs => $prefs, focus_tree => $focus_tree);
$editor->run();
MAIN
