#!/usr/bin/env perl
# Build script: assembles single-file zepto from modules
use strict;
use warnings;

# Order matters for dependencies
my @modules = qw(
    lib/Zepto/Buffer.pm
    lib/Zepto/Document.pm
    lib/Zepto/View.pm
    lib/Zepto/InputParser.pm
    lib/Zepto/Theme.pm
    lib/Zepto/Preferences.pm
    lib/Zepto/Terminal.pm
    lib/Zepto/Config.pm
    lib/Zepto/FilePicker.pm
    lib/Zepto/Chars.pm
    lib/Zepto/Renderer.pm
    lib/Zepto/Editor.pm
    lib/Zepto/Editor/Commands.pm
    lib/Zepto/Editor/Menu.pm
);

# Header
print <<'HEADER';
#!/usr/bin/env perl
# =============================================================================
# Zepto - A minimal terminal text editor
# =============================================================================
# Single-file distribution. Run: zepto [filename]
# https://github.com/joewalnes/zepto
# 2026 Joe Walnes <joe@walnes.com>
#
# This file is auto-generated by 'make build'. Do not edit directly.
# Edit the source modules in lib/Zepto/ instead.
# =============================================================================

use strict;
use warnings;
use utf8;
use 5.010001;

HEADER

# Include each module
for my $file (@modules) {
    open my $fh, '<', $file or die "Cannot open $file: $!";
    my $content = do { local $/; <$fh> };
    close $fh;
    
    # Remove shebang if present
    $content =~ s/^#!.*\n//;
    
    # Remove 'use Zepto::*' lines (they're all inline now)
    # Handles both 'use Zepto::Foo;' and 'use Zepto::Foo qw(...);'
    $content =~ s/^use Zepto::\w+(?:::\w+)*(?:\s+qw\([^)]*\))?;\n//gm;
    
    # Remove __END__ and POD (keep it compact)
    $content =~ s/\n__END__.*//s;

    # Strip comment-only lines (lines starting with #)
    $content =~ s/^[ \t]*#.*\n//gm;

    # Add section header (handle nested modules like Editor/Commands)
    my ($pkg) = $file =~ m{lib/Zepto/(.+)\.pm$};
    $pkg =~ s{/}{::}g;
    print "# " . "=" x 77 . "\n";
    print "# $pkg\n";
    print "# " . "=" x 77 . "\n";
    print $content;
    print "\n";
}

# Main entry point
print <<'MAIN';
# =============================================================================
# Main
# =============================================================================
package main;

# Parse command line options
my $file;
my $no_powerline = 0;

for my $arg (@ARGV) {
    if ($arg eq '--no-powerline' || $arg eq '-P') {
        $no_powerline = 1;
    } elsif ($arg eq '--help' || $arg eq '-h') {
        print "Usage: zepto [options] [file]\n";
        print "Options:\n";
        print "  --no-powerline, -P  Disable Powerline/Nerd Font glyphs\n";
        print "  --help, -h          Show this help\n";
        print "\nEnvironment:\n";
        print "  ZEPTO_POWERLINE=0   Disable Powerline glyphs by default\n";
        exit 0;
    } elsif ($arg !~ /^-/) {
        $file = $arg;
    }
}

# Check environment variable for powerline setting
my $powerline = 1;  # Default ON
if ($no_powerline || (defined $ENV{ZEPTO_POWERLINE} && $ENV{ZEPTO_POWERLINE} eq '0')) {
    $powerline = 0;
}

# Create preferences with powerline setting
my $prefs = Zepto::Preferences->new(powerline => $powerline);
Zepto::Chars->set_enabled($powerline);

my $editor = Zepto::Editor->new(file => $file, prefs => $prefs);
$editor->run();
MAIN
