#!/usr/bin/env perl
# Build script: assembles single-file zepto from modules
use strict;
use warnings;
use utf8;
use File::Find;
use POSIX qw(strftime);

binmode(STDOUT, ':utf8');

# Build version: env override > git tag > CalVer date
my $VERSION = $ENV{ZEPTO_VERSION}
    || `git describe --tags --exact-match 2>/dev/null` =~ s/\s+$//r
    || strftime('%Y.%m.%d', localtime);
chomp $VERSION;

# Recursively find all .pm files under lib/
my @all_modules;
find(sub {
    return unless /\.pm$/;
    push @all_modules, $File::Find::name;
}, 'lib');

# Sort modules by dependency order:
# 1. Core modules (no subdir) - sorted alphabetically but with specific order
# 2. Syntax/Base.pm must come before other Syntax modules
# 3. Syntax/* modules alphabetically
# 4. Editor.pm before Editor/* submodules
# 5. Highlighter and Renderer after Syntax modules
# 6. Everything else

my %priority = (
    # Core modules first (lower number = higher priority)
    'lib/Zepto/Buffer.pm'      => 10,
    # VCS modules must come before Document (which uses them)
    'lib/Zepto/VCS/Provider.pm' => 11,  # Provider first (has the registry)
    'lib/Zepto/VCS/Git.pm'      => 12,  # Git second (registers with Provider)
    'lib/Zepto/Diff.pm'         => 13,  # Diff module for VCS
    'lib/Zepto/Document.pm'     => 14,
    'lib/Zepto/View.pm'         => 15,
    'lib/Zepto/InputParser.pm'  => 16,
    'lib/Zepto/Theme.pm'        => 17,
    'lib/Zepto/Preferences.pm'  => 18,
    'lib/Zepto/ImageConverter.pm' => 18.5,  # Before Terminal (which uses it)
    'lib/Zepto/Terminal.pm'     => 19,
    'lib/Zepto/Config.pm'       => 20,
    'lib/Zepto/Chars.pm'        => 21,
    'lib/Zepto/FileTree.pm'     => 22,
    'lib/Zepto/FileSearchEngine.pm' => 25,
    # Minimap has no Zepto deps — must come before Renderer which derives constants from it
    'lib/Zepto/Minimap.pm'     => 23,
    # Syntax/Base must come first among Syntax modules
    'lib/Zepto/Syntax/Base.pm' => 50,
    # Highlighter needs all Syntax modules loaded
    'lib/Zepto/Highlighter.pm' => 100,
    # Completion modules (between Highlighter and Renderer)
    'lib/Zepto/Completion/Controller.pm'              => 105,
    'lib/Zepto/Completion/KeywordProvider.pm'          => 106,
    'lib/Zepto/Completion/CrossBufferWordProvider.pm'  => 107,
    'lib/Zepto/Completion/RecentProvider.pm'           => 107.5,
    'lib/Zepto/Completion/SnippetProvider.pm'          => 108,
    'lib/Zepto/Completion/PathProvider.pm'             => 109,
    # Renderer needs Highlighter
    'lib/Zepto/Renderer.pm'    => 110,
    # HelpDocs before CommandRegistry (doc commands reference it)
    'lib/Zepto/HelpDocs.pm'        => 114,
    # CommandRegistry must come before Editor (Palette references its constants)
    'lib/Zepto/CommandRegistry.pm' => 115,
    # Editor needs everything above
    'lib/Zepto/Editor.pm'      => 120,
);

sub module_priority {
    my ($path) = @_;

    # Check explicit priority
    return $priority{$path} if exists $priority{$path};

    # Syntax modules (except Base) get priority 60
    return 60 if $path =~ m{lib/Zepto/Syntax/};

    # Editor submodules get priority 130
    return 130 if $path =~ m{lib/Zepto/Editor/};

    # Everything else gets 200
    return 200;
}

my @modules = sort {
    module_priority($a) <=> module_priority($b)
    || $a cmp $b  # Alphabetical within same priority
} @all_modules;

# Header
print <<'HEADER';
#!/usr/bin/env perl
# =============================================================================
# Zepto - A minimal terminal text editor
# =============================================================================
# Single-file distribution. Run: zepto [filename]
# https://github.com/joewalnes/zepto
# 2026 Joe Walnes <joe@walnes.com>
#
# This file is auto-generated by 'make build'. Do not edit directly.
# Edit the source modules in lib/Zepto/ instead.
# =============================================================================

use strict;
use warnings;
use utf8;
use 5.010001;

HEADER

# Include each module
for my $file (@modules) {
    open my $fh, '<', $file or die "Cannot open $file: $!";
    my $content = do { local $/; <$fh> };
    close $fh;

    # Remove shebang if present
    $content =~ s/^#!.*\n//;

    # Convert 'use parent' to @ISA (parent pragma tries to load from filesystem)
    $content =~ s/^use parent\s+'(Zepto::\S+)';\n/our \@ISA = ('$1');\n/gm;

    # Convert Zepto::Syntax::Base import to explicit import call (for Exporter constants)
    # This must happen before removing other use statements
    $content =~ s/^use Zepto::Syntax::Base;[^\n]*\n/BEGIN { Zepto::Syntax::Base->import(); }\n/gm;

    # Remove other 'use Zepto::*' lines (they're all inline now)
    # Handles 'use Zepto::Foo;', 'use Zepto::Foo qw(...);', and lines with trailing comments
    $content =~ s/^use Zepto::\w+(?:::\w+)*(?:\s+qw\([^)]*\))?;[^\n]*\n//gm;

    # Remove __END__ and POD (keep it compact)
    $content =~ s/\n__END__.*//s;

    # Strip comment-only lines (lines starting with #)
    $content =~ s/^[ \t]*#.*\n//gm;

    # Embed help docs into HelpDocs module (after comment stripping, since
    # heredoc content contains # lines that must be preserved)
    if ($file =~ m{HelpDocs\.pm$}) {
        my $embed_code = '';
        for my $doc_file (sort glob('docs/help/*.md')) {
            open my $dfh, '<:utf8', $doc_file or die "Cannot open $doc_file: $!";
            my $doc_content = do { local $/; <$dfh> };
            close $dfh;
            (my $doc_id = $doc_file) =~ s{^docs/help/(.+)\.md$}{$1};
            $embed_code .= "\$EMBEDDED{'$doc_id'} = <<'__END_DOC_${doc_id}__';\n";
            $embed_code .= $doc_content;
            $embed_code .= "__END_DOC_${doc_id}__\n";
        }
        # The marker was stripped as a comment; inject after %EMBEDDED declaration
        $content =~ s/(my %EMBEDDED;\n)/$1$embed_code/;
    }

    # Inject build version into Editor module
    $content =~ s/our \$VERSION = 'dev';/our \$VERSION = '$VERSION';/
        if $file =~ m{Editor\.pm$};

    # Add section header (handle nested modules like Editor/Commands)
    my ($pkg) = $file =~ m{lib/Zepto/(.+)\.pm$};
    $pkg =~ s{/}{::}g;
    print "# " . "=" x 77 . "\n";
    print "# $pkg\n";
    print "# " . "=" x 77 . "\n";

    # Wrap content in a block to create separate lexical scope for each module.
    # This prevents "my variable $X masks earlier declaration" warnings when
    # modules like Syntax::Perl and Syntax::Python both declare my $KEYWORDS.
    print "{\n";
    print $content;
    print "}\n";
    print "\n";
}

# Main entry point
print <<'MAIN';
# =============================================================================
# Main
# =============================================================================
package main;
use Cwd ();
use File::Copy ();
use File::Path ();
use File::Basename ();

# -----------------------------------------------------------------------------
# --version
# -----------------------------------------------------------------------------
if (grep { $_ eq '--version' || $_ eq '-v' } @ARGV) {
    print "zepto $Zepto::Editor::VERSION\n";
    exit 0;
}

# -----------------------------------------------------------------------------
# --install [path]
# -----------------------------------------------------------------------------
if (grep { $_ eq '--install' } @ARGV) {
    _zepto_install();
    exit 0;
}

sub _zepto_install {
    binmode(STDOUT, ':utf8');
    my $use_color = !$ENV{NO_COLOR} && -t STDOUT && ($ENV{TERM} || '') ne 'dumb';
    my $BOLD  = $use_color ? "\e[1m"    : '';
    my $DIM   = $use_color ? "\e[2m"    : '';
    my $GREEN = $use_color ? "\e[32m"   : '';
    my $YELLOW= $use_color ? "\e[33m"   : '';
    my $RED   = $use_color ? "\e[31m"   : '';
    my $CYAN  = $use_color ? "\e[36m"   : '';
    my $RESET = $use_color ? "\e[0m"    : '';
    my $CHECK = $use_color ? "${GREEN}\x{2713}${RESET}" : 'ok';
    my $WARN  = $use_color ? "${YELLOW}\x{25b2}${RESET}" : '!!';
    my $FAIL  = $use_color ? "${RED}\x{2717}${RESET}" : 'FAIL';

    my $_step = sub { printf "  %-22s %s\n", $_[0], $_[1] };

    # Parse --install [path] from @ARGV
    my $custom_path;
    for my $i (0 .. $#ARGV) {
        if ($ARGV[$i] eq '--install' && defined $ARGV[$i+1] && $ARGV[$i+1] !~ /^-/) {
            $custom_path = $ARGV[$i+1];
            last;
        }
    }

    my $dest;
    if (defined $custom_path) {
        # If path is a directory, append /zepto; otherwise use as-is
        $dest = (-d $custom_path) ? "$custom_path/zepto" : $custom_path;
    } else {
        $dest = "$ENV{HOME}/.local/bin/zepto";
    }

    # Resolve ~ just in case
    $dest =~ s{^~}{$ENV{HOME}};

    my $dest_dir = File::Basename::dirname($dest);
    my $display_dest = $dest;
    $display_dest =~ s{^\Q$ENV{HOME}\E}{~};
    my $display_dir = $dest_dir;
    $display_dir =~ s{^\Q$ENV{HOME}\E}{~};

    # Banner
    print "\n";
    print "  ${BOLD}zepto installer${RESET}\n";
    print "  ${DIM}A modern terminal text editor${RESET}\n";
    print "\n";

    # 1. Check Perl version
    my $perl_v = sprintf('%vd', $^V);
    if ($^V ge v5.10.0) {
        $_step->("Checking Perl...", "v${perl_v} ${CHECK}");
    } else {
        $_step->("Checking Perl...", "v${perl_v} ${FAIL}");
        print "\n  ${RED}Perl 5.10+ required.${RESET}\n\n";
        exit 1;
    }

    # 2. Read our own source
    my $source_path = $0;
    if (!-f $source_path || !-r $source_path) {
        $_step->("Reading source...", "${FAIL}");
        print "\n  ${RED}Cannot read $0. Run with a file path, not a pipe.${RESET}\n";
        print "  ${DIM}Use: perl zepto --install${RESET}\n\n";
        exit 1;
    }

    open(my $src_fh, '<:raw', $source_path)
        or do { $_step->("Reading source...", "${FAIL} $!"); exit 1 };
    my $source = do { local $/; <$src_fh> };
    close $src_fh;

    # 3. Create destination directory
    if (!-d $dest_dir) {
        eval { File::Path::make_path($dest_dir) };
        if ($@) {
            $_step->("Creating ${display_dir}...", "${FAIL}");
            print "  ${RED}$@${RESET}\n";
            exit 1;
        }
        $_step->("Creating ${display_dir}...", "${CHECK}");
    }

    # 4. Write to destination
    my $updating = -f $dest;
    open(my $dst_fh, '>:raw', $dest)
        or do { $_step->("Installing to ${display_dest}...", "${FAIL} $!"); exit 1 };
    print $dst_fh $source;
    close $dst_fh;
    chmod 0755, $dest;
    my $verb = $updating ? "Updated" : "Installed to";
    $_step->("${verb} ${display_dest}...", "${CHECK}");

    # 5. Check if destination dir is in PATH
    my $in_path = 0;
    my $abs_dest_dir = Cwd::abs_path($dest_dir) || $dest_dir;
    for my $p (split /:/, $ENV{PATH} || '') {
        my $abs_p = Cwd::abs_path($p) || $p;
        if ($abs_p eq $abs_dest_dir) {
            $in_path = 1;
            last;
        }
    }

    if ($in_path) {
        $_step->("Checking PATH...", "in PATH ${CHECK}");
    } else {
        $_step->("Checking PATH...", "${display_dir} not in PATH ${WARN}");
        print "\n";
        my $shell = $ENV{SHELL} || '/bin/sh';
        my $shell_name = File::Basename::basename($shell);
        my $rc_file;
        if    ($shell_name eq 'zsh')  { $rc_file = '~/.zshrc' }
        elsif ($shell_name eq 'bash') { $rc_file = '~/.bashrc' }
        elsif ($shell_name eq 'fish') { $rc_file = '~/.config/fish/config.fish' }
        else                          { $rc_file = '~/.profile' }

        if ($shell_name eq 'fish') {
            print "  Add to ${BOLD}${rc_file}${RESET}:\n";
            print "  ${CYAN}set -gx PATH ${dest_dir} \$PATH${RESET}\n";
        } else {
            print "  Add to ${BOLD}${rc_file}${RESET}:\n";
            print "  ${CYAN}export PATH=\"${dest_dir}:\$PATH\"${RESET}\n";
        }
        print "\n  Then: ${DIM}source ${rc_file}${RESET}\n";
        print "\n";
    }

    # 6. Self-check: run the installed copy
    my $check_output = `"$dest" --version 2>&1`;
    chomp $check_output if defined $check_output;
    if ($? == 0 && defined $check_output && $check_output =~ /^zepto\s/) {
        $_step->("Self-check...", "${check_output} ${CHECK}");
    } else {
        $_step->("Self-check...", "${FAIL}");
        print "  ${RED}Installed binary did not respond to --version${RESET}\n";
    }

    # Done
    print "\n";
    if ($in_path) {
        print "  ${GREEN}${BOLD}Ready!${RESET} Run: ${BOLD}zepto myfile.txt${RESET}\n";
    } else {
        print "  ${GREEN}${BOLD}Ready!${RESET} Run: ${BOLD}${dest} myfile.txt${RESET}\n";
    }
    print "\n";
}

# Parse command line options
my @files;
my $no_nerd_font = 0;
my $no_tree = 0;
my $force_tree = 0;

for my $arg (@ARGV) {
    if ($arg eq '--no-nerd-font' || $arg eq '--no-powerline' || $arg eq '-P') {
        $no_nerd_font = 1;
    } elsif ($arg eq '--no-tree') {
        $no_tree = 1;
    } elsif ($arg eq '--tree') {
        $force_tree = 1;
    } elsif ($arg eq '--help' || $arg eq '-h') {
        print "Usage: zepto [options] [file ...]\n";
        print "Options:\n";
        print "  --install [path]    Install zepto (default: ~/.local/bin/zepto)\n";
        print "  --version, -v       Show version\n";
        print "  --no-nerd-font, -P  Disable Nerd Font glyphs\n";
        print "  --tree              Show file tree on startup\n";
        print "  --no-tree           Hide file tree on startup\n";
        print "  --help, -h          Show this help\n";
        print "\nEnvironment:\n";
        print "  ZEPTO_NERD_FONT=0   Disable Nerd Font glyphs by default\n";
        print "  ZEPTO_TREE=0        Hide file tree by default\n";
        exit 0;
    } elsif ($arg !~ /^-/) {
        push @files, $arg;
    }
}

# Special case: if the only non-option arg is a directory, chdir to it
my $focus_tree = 0;
if (@files == 1 && -d $files[0]) {
    chdir $files[0] or die "Cannot chdir to $files[0]: $!\n";
    @files = ();
    $focus_tree = 1;
}

# Check environment variable for nerd font setting
my $nerd_font = 1;  # Default ON
if ($no_nerd_font || (defined $ENV{ZEPTO_NERD_FONT} && $ENV{ZEPTO_NERD_FONT} eq '0')) {
    $nerd_font = 0;
}

# Determine show_tree: explicit flag > env var > default (hidden when opening files)
my $show_tree = 1;  # Default ON
if ($force_tree) {
    $show_tree = 1;
} elsif ($no_tree || (defined $ENV{ZEPTO_TREE} && $ENV{ZEPTO_TREE} eq '0')) {
    $show_tree = 0;
} elsif (@files >= 1 && !$focus_tree) {
    # Opening specific files (not a directory) — hide tree by default
    $show_tree = 0;
}

# Create preferences
my $prefs = Zepto::Preferences->new(nerd_font => $nerd_font, show_tree => $show_tree);
Zepto::Chars->set_enabled($nerd_font);

my $editor = Zepto::Editor->new(files => \@files, prefs => $prefs, focus_tree => $focus_tree);
$editor->run();
MAIN
